config/routes.rb
Rails.application.routes.draw do
  get 'books/new'
  # For details on the DSL available within this file, see http://guides.rubyonrails.org/routing.html
  root 'books#top'
  get 'top' => 'books#top'
  post 'books' => 'books#create'
  get 'books' => 'books#index'
  get 'books/:id' => 'books#show', as: 'book'
  get 'books/:id/edit' => 'books#edit', as: 'edit_book'
  patch 'books/:id' => 'books#update', as: 'update_book'
  delete 'books/:id' => 'books#destroy', as:'destroy_book'
  resources :books
end

app/models/application_record.rb
class ApplicationRecord < ActiveRecord::Base
  self.abstract_class = true
end

app/models/book.rb
class Book < ApplicationRecord
  validates :title,presence: true
  validates :body,presence: true
end

app/controllers/application_controller.rb
class ApplicationController < ActionController::Base
end

app/controllers/books_controller.rb
class BooksController < ApplicationController
  def top
  end
  def new
    @book = Book.new
  end
  def create
    @book = Book.new(book_params)
    @books = Book.all
    if @book.save
    redirect_to book_path(@book.id), notice: 'Book was successfully created.'
    else
   render :index
    end
  end
  def index
    @books = Book.all
    @book = Book.new
  end
  def show
    @book = Book.find(params[:id])
  end
  def edit
    @book = Book.find(params[:id])
  end
  def update
    @book = Book.find(params[:id])
    if @book.update(book_params)
    redirect_to book_path(@book.id), notice: 'Book was successfully updated.'
    else
    render :edit
    end
  end
  def destroy
    book = Book.find(params[:id])
    if book.destroy
    redirect_to books_path, notice: 'Book was successfully destroyed.'
    end
  end
  private
  def book_params
    params.require(:book).permit(:title, :body)
  end
end

app/controllers/todolists_controller.rb
class TodolistsController < ApplicationController
  def new
    @book = Book.new
  end
  def create
    book = Book.new(book_params)
    book.save
    redirect_to todolists_path(book.id)
  end
  def index
    @books = Book.all
  end
  def show
    @book = Book.find(params[:id])
  end
  def edit
    @book = Book.find(params[:id])
  end
  def update
    book = Book.find(params[:id])
    book.update(book_params)
    redirect_to todolist_path(book.id)
  end
  def destroy
    book = Book.find(params[:id])
    book.destroy
    redirect_to todolists_path
  end
  private
  def book_params
    params.require(:book).permit(:title, :body)
  end
end

app/helpers/application_helper.rb
module ApplicationHelper
end

app/helpers/books_helper.rb
module BooksHelper
end

app/helpers/todolists_helper.rb
module TodolistsHelper
end

app/views/books/edit.html.erb
<h1>Editing Book</h1>
<% if @book.errors.any? %>
  <div class="alert alert-warning">
    <ul>
        <li><%= @book.errors.count %>error</li>
      <% @book.errors.full_messages.each do |message| %>
        <li><%= message %></li>
      <% end %>
    </ul>
  </div>
<% end %>
<%= form_with model:@book, url:"/books/#{@book.id}", local:true do |f| %>
  <h4>Title</h4>
  <%= f.text_field :title %>
  <h4>Body</h4>
  <%= f.text_area :body %>
  <br><%= f.submit 'Update Book' %></br>
  <br><%= link_to "show", book_path(@book.id) %> | <%= link_to "Back", books_path %>
  </br>
<% end %>

app/views/books/index.html.erb
<p id="notice">
 <%=  notice %> 
<h1>Books</h1>
<table>
<thead>
    <tr>
    <th>Title</th>
    <th>Body</th>
    <th></th>
    </tr>
</thead>

<tbody>
  <% @books.each do |book| %>
     <tr>
     <td>
     <%= book.title %>
     </td>
     <td>
     <%= book.body %>
     </td>
     <td>
     <%= link_to "show", book_path(book.id) %>
     <%= link_to "edit", edit_book_path(book.id) %>
     <%= link_to "destroy", destroy_book_path(book.id),method: :delete, "data-confirm" => "Are you sure?" %>
     </td>
     </tr>
  <% end %>
</tbody>
</table>
<h1>New book</h1>
<% if @book.errors.any? %>
  <div class="alert alert-warning">
    <ul>
        <li><%= @book.errors.count %>error</li>
      <% @book.errors.full_messages.each do |message| %>
        <li><%= message %></li>
      <% end %>
    </ul>
  </div>
<% end %>

<%= form_with model:@book, local:true do |f| %>

<p>Title</p>
<%= f.text_field :title %>

<p>Body</p>
<%= f.text_area :body %>
<br><%= f.submit 'Create Book' %></br>


<% end %>

app/views/books/new.html.erb
<h1>New book</h1>
<%= form_with model:@book, url:'/books', local:true do |f| %>

<p>Title</p>
<%= f.text_field :title %>

<p>Body</p>
<%= f.text_area :body %>
<%= f.submit 'Create Book' %>
<% end %>

app/views/books/show.html.erb
<p id="notice">
 <%=  notice %> 
<h2>Title:</h2>
<p><%= @book.title %></p>
<h2>Body:</h2>
<p><%= @book.body %></p>
<br>
<%= link_to "Edit", edit_book_path(@book.id) %> | <%= link_to "Back", books_path %>
</br>

app/views/books/top.html.erb
<h1>ようこそ<strong> Bookers</strong> へ！</h1>

<p><strong>Bookers</strong> では、さまざまな書籍に関するあなたのの意見や</p>

<p>印象を共有し交換することができます</p>

<%= link_to "start", books_path %>

app/views/layouts/application.html.erb
<!DOCTYPE html>
<html>
  <head>
    <title>Bookers</title>
    <%= csrf_meta_tags %>
    <%= csp_meta_tag %>

    <%= stylesheet_link_tag    'application', media: 'all', 'data-turbolinks-track': 'reload' %>
    <%= javascript_include_tag 'application', 'data-turbolinks-track': 'reload' %>
  </head>

  <body>
    <%= yield %>
  </body>
</html>

app/views/todolists/edit.html.erb
<h1>Book</h1>
<%= form_with model:@book, url:"/todolists/#{@book.id}", local:true do |f| %>
  <h4>Title</h4>
  <%= f.text_field :title %>
  <h4>Body</h4>
  <%= f.text_area :body %>
  <%= f.submit 'Edit' %>
  <%= f.submit 'Back' %>
<% end %>

app/views/todolists/index.html.erb
<h1>Books</h1>
<table>
<thead>
    <tr>
    <th>Title</th>
    <th>Body</th>
    <th></th>
    </tr>
</thead>

<tbody>
     <% @books.each do |book| %>
     <tr>
     <td>
     <%= book.title %>
     </td>
     <td>
     <%= book.body %>
     </td>
     <td>
     <%= link_to "show", todolist_path(book.id) %>
     <%= link_to "edit", edit_todolist_path(book.id) %>
     <%= link_to "destroy", destroy_todolist_path(book.id),method: :delete, "data-confirm" => "Are you sure?" %>
     </td>
     </tr>
     <% end %>
</tbody>
</table>
<h1>New book</h1>
<%= form_with model:@book, url:'/todolists', local:true do |f| %>

<p>Title</p>
<%= f.text_field :title %>

<p>Body</p>
<%= f.text_area :body %>
<br><%= f.submit 'Create Book' %></br>

<% end %>

app/views/todolists/new.html.erb
<h1>New book</h1>
<%= form_with model:@book, url:'/todolists', local:true do |f| %>

<p>Title</p>
<%= f.text_field :title %>

<p>Body</p>
<%= f.text_area :body %>
<%= f.submit 'Create Book' %>
<% end %>

app/views/todolists/show.html.erb
<h2>Title</h2>
<p><%= @book.title %></p>
<h2>Body</h2>
<p><%= @book.body %></p>
<%= link_to "Edit", edit_todolist_path(@book.id) %>